### ISSUE TITLE
File Service not provided 

### ISSUE THREAD

**Issue by kanutan93** [formio/angular-formio#149]
Message "File Service not provided" when i select file from FileComponent. Do you have guide, about how i can do file uploading with your component?

**Comment by travist** [comment]
You are running into this https://github.com/formio/formio.js/blob/585bdc61159c7ab4b50bfff24c3edd7dba7587fe/src/components/file/File.js#L426

This is caused because the renderer does not know how to create the formio object which requires an API endpoint. This happens when you do not provide a ```src``` or ```url``` parameter to the component when embedding it (such as if you were to just use ```form```).
