### ISSUE TITLE
How to build and register a (angular-) custom component with prime ng?

### ISSUE THREAD

**Issue by avan2s** [formio/angular-formio#201]
Hello,

we would like to add an angular custom component, whose template is mixed with prime-ng components like the pie chart etc. I have alredy read the 
 [MatrixExample](https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075), but the import statements don't work anymore. I figured out how to change the import statements in order to get the custom component to work (click: [here](https://github.com/avan2s/angular-app-starterkit/blob/master/src/app/custom-component.ts)). Anyway this is not an angular component solution by extending from base javascript class - BaseComponent.

Now we would like to create an Angular component with prime ng stuff and register it for Formio as a custom component. Is this possible? If yes how to register and render it? :)

I would be really grateful for your help.

Thanks a lot and best regards,
Andy

**Comment by wag110894** [comment]
Hello Andy,

This is William with the Form.io support team. Thanks for reaching out!

Yes this is possible, but any custom components are made within the "core" javascript library (formio/formio.js) instead of the Angular library. The Angular library is just a simple wrapper around our "core" renderer, so once you register your custom component within that renderer, then it will show up automatically when you render that form in Angular.

We also have support packages available for training or feature requests if you are interested

Thanks,

William Gay
Form.io Developer Support

**Comment by travist** [comment]
I just created some examples of a custom component in Angular. You can see it in the Angular Demo application @ https://github.com/formio/angular-demo.

Here is the custom component.

https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js

And here is how you register it within your application.

https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L19

Hope this helps.

**Comment by adelaaji** [comment]
> 
> 
> I just created some examples of a custom component in Angular. You can see it in the Angular Demo application @ https://github.com/formio/angular-demo.
> 
> Here is the custom component.
> 
> https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js
> 
> And here is how you register it within your application.
> 
> https://github.com/formio/angular-demo/blob/master/src/app/app.module.ts#L19
> 
> Hope this helps.

thanks alot, 
but Checkmatrix doesn't  shown!!

**Comment by merobal** [comment]
Inspired by this issue I added abilities to register an Angular component directly as custom formio field: https://github.com/formio/angular-formio/pull/374

Documentation: https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements
