### ISSUE TITLE
Data binding between multiple formio forms

### ISSUE THREAD

**Issue by krixerx** [formio/angular-formio#209]
About half year ago, two way data binding was supported and this was very convenient solution.

But now, only solution is to listen form "change" event and emit "refresh" event to other forms.
This is not convenient at all because we have to synchronize data between forms manually. 
Angular2+ main idea was that developers should not bind data manually.
Are there any plans to improve it in angular-formio?

**Comment by krixerx** [comment]
Actually i think i solved my problem easily.
Lets say we have 3 forms. form3 depends on form1 and form2. form2 dependes on form1.

HTML part is in this case:
```
<div class="card">
  <div class="card-body">
    <h5 class="card-title">A1</h5>
    <div class="card bg-light p-3">
      <formio src="https://form1schema" [refresh]="refreshForm1" [submission]="submission" (change)="setSubmission($event,'form1')"></formio>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">A2</h5>
    <div class="card bg-light p-3">
      <formio src="https://form2schema" [refresh]="refreshForm2" [submission]="submission" (change)="setSubmission($event,'form2')"></formio>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">A3</h5>
    <div class="card bg-light p-3">
      <formio src="https://form3schema" [refresh]="refreshForm3" [submission]="submission" (change)="setSubmission($event,'form3')"></formio>
    </div>
  </div>
</div>

```
And  controller part:

```
  public refreshForm1 = new EventEmitter();
  public refreshForm2 = new EventEmitter();
  public refreshForm3 = new EventEmitter();

  public setSubmission(submission: any, formId: string): void {
    if (submission.changed && submission.changed.component.key) {
      this.submission.data[submission.changed.component.key] = submission.changed.value;
      // form2 depends on form1
      if (formId === 'form1') {
        this.refreshForm2.emit({
          submission: this.submission
        });
      }
      // form3 depends on form2
      if (formId === 'form2') {
        this.refreshForm3.emit({
          submission: this.submission
        });
      }
    }
  }
```

Solved for me.

**Comment by wag110894** [comment]
Hello,

Thanks for the feedback! 

The reason for the change was that two way data binding within the form caused many issues in the form, particularly around the principle that a component should only ever change its own value. Otherwise you run into race conditions where two components could attempt to change one component’s value at the same time. 

The way we got around this was to allow components to trigger events and other components to respond to those events but changing their value. This is has a little more configuration but makes things more understandable and debuggable when trying to figure out "why did that field's value change?"

Please let me know if you need any further information.

Thanks, 
William Gay 
Form.io Developer Support
