### ISSUE TITLE
Can not reference specific version of dependent package

### ISSUE THREAD

**Issue by mneofit** [formio/angular-formio#304]
There is an issue in formiojs [#1270 Content Component Error](https://github.com/formio/formio.js/issues/1270) that could be solved in angular-formio by referencing concrete version of package `@ckeditor/ckeditor5-build-classic`. For example, `v12.0.0` of this package can make the trick.

As for current moment it requires to make some bad smell alterations to make it work (reference a package, retrieve specific export and put it into `window`). 

If there would be a built-in possibility to reference it, it would allow to get round this kind of issues related to formiojs itself.

**Comment by travist** [comment]
The problem here is that the editors are lazy-loaded due to trying to make the "editor" configurable. There is a way to create a "build" that does not do this by adding the following to your custom renderer.

```js
import BaseComponent from 'formiojs/components/base/Base';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

BaseComponent.prototype.addCKE = function (element, settings, onChange) {
  settings = settings || {};
  return ClassicEditor.create(element, settings).then(editor => {
    editor.model.document.on('change', () => onChange(editor.data.get()));
    return editor;
  });
};
```

This is used much like how you see in our [Custom Renderer Repo](https://github.com/formio/custom-renderer). You would make that change to this file https://github.com/formio/custom-renderer/blob/master/components/Base.js.

Now, in Angular, you would just include your renderer using the "renderer" property on the <formio> directive.
