### ISSUE TITLE
Formio dependencies 

### ISSUE THREAD

**Issue by fzucaro** [formio/angular-formio#390]
Hello,
i just start to use formio for a new project. I set-up the project using angular-cli and use npm install in order to include formio libraries. After download all dependencies and include module and providers i have thie error: 
**ERROR in node_modules/angular-formio/formio.common.d.ts(3,43): error TS2307: Cannot find module '@angular/elements**'.

I use angular-cli c. 7,3,9 and npm install angular-formio": "^4.3.0-beta.3".

**Comment by merobal** [comment]
`@angular/elements` is a peer dependency of `angular-formio` version `^4.3.0`.
Please install with `npm i @angular/elements`

**Comment by fzucaro** [comment]
Thanks a lot, it'ok and upgrading all to angular 8 i don't have exception on browser console

**Comment by barkat-uipl** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/93926484/140755340-82cc0009-4c77-4fdd-867d-36a0b3320247.png)


I am getting this error in

Angular CLI: 9.1.3
Node: 12.14.1
OS: win32 x64
Angular: 9.1.3
 but npm i @angular/elements the issue is not fixed if I install this its showing different error.
