### ISSUE TITLE
[BUG] 4.3.x is incompatible with Angular 7

### ISSUE THREAD

**Issue by bh-adrienne** [formio/angular-formio#412]
## Environment
Angular : 7.2.15

- Hosting type
  - [] Form.io
  - [x] Local deployment
  
- Formio.js version: 4.7.8
- Frontend framework: Angular 7.2.15
- Browser: all 
- Browser version: - 

## Steps to Reproduce
1.  In Angular 7.2.15 project, I updated my package.json to try and use Angular 4.3.0
2. Running 'ng serve' command

## Expected behavior

Clean build and run. 

## Observed behavior
Entire application gives blank screen now, build error is: 
```
WARNING in ./node_modules/angular-formio/custom-component/custom-tags.service.js 25:59-80
"export 'ɵɵdefineInjectable' (imported as 'i0') was not found in '@angular/core'
```
And my entire application fails to run. 
Downgrading angular-formio to 4.2.12 fixes this issue. 

In addition, 4.3.2 introduces an explicit dependency to the Angular 8 library: 

If the intention is to stop support for Angular 7 at 4.2, please reply and document this end of life support on the front page. 

Otherwise, a quick google search reveals this issue has something to do with how a package is compiled: 
https://github.com/angular/angular/issues/30413

The provided workaround on that ticket does not work because all it actually does is upload the user's project to Angular 8.

**Comment by merobal** [comment]
Initially the `@angular/elements` package was added as peer dependency, so please try `4.3.0` explicit version and install `@angular/elements` version 7. Let me know if it works.

@travist asked me to add `@angular/elements` as project dependency to avoid unnecessary peer dependencies and additional installs, so I added the latest version, which is the version 8, and that caused this problem. Related: https://github.com/formio/angular-formio/issues/398

**Comment by bh-adrienne** [comment]
I tried with 4.3.0 and @angular/elements 7.2.15 and I still get the build errror. 

WARNING in ./node_modules/angular-formio/custom-component/custom-tags.service.js 25:59-80
"export 'ɵɵdefineInjectable' (imported as 'i0') was not found in '@angular/core'

Looks like the @angular/elements thing, while potentially still a problematic dependecy for those of us on Angular 7, is possibly not the root cause of this issue.

**Comment by moeVdm** [comment]
I am getting this build error as well, any news on how we can get this to work with Angular 7?

**Comment by blochealth** [comment]
@merobal  this is now officially blocking me from using the new formio.js version, which contains a different bug fix my company paid to have expedited. Sort of defeats the purpose if I can't use it. Is there a way to get this moving?   

As I noted, it does not appear to actually be related to your hypothesis that @angular/elements@8 is causing the issue, because I still get the issue when both my top level package.json @angular/elements version is 7.2.15 AND when I modify the angular-formio nested/peer dependencies to use 7.2.15.

**Comment by travist** [comment]
@blochealth we will put this on our expedited list of things to resolve. I will take a look either today or tomorrow to work out a resolution.

**Comment by travist** [comment]
So after some investigation, it seems that the issue comes from this one single line...

***/src/custom-component/custom-tags.service.ts***
```js
@Injectable({ providedIn: 'root' })
```
If I change it to the following it works in Angular 7.

***/src/custom-component/custom-tags.service.ts***
```js
@Injectable()
```

The only caveat to this is that anyone using CustomTags will need to make sure to manually provide that service in their applications.

**Comment by merobal** [comment]
Nice catch, this can be provided in the module lib too, I can fix this after holidays

**Comment by travist** [comment]
This was urgent so I went ahead and fixed it by just including the service in the base AngularFormio module. I hope that is sufficient. Regardless, this has been fixed with version 4.3.13.  I updated the starterkit (which is still Angular 7) to illustrate it works @ https://github.com/formio/angular-app-starterkit

**Comment by bh-adrienne** [comment]
@travist , sorry, but your fix now causes a new error in the angular-app-starterkit.  It builds, but 
a from scratch checkout of the starterkit and 'npm install' now results in the following error in the console: 

`Error: "Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten. Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)"
    Angular 5
    notify es.promise.js:114
    flush microtask.js:26
    Angular 3`


I still can't actually use the new version. This same error happens in my own project.

**Comment by travist** [comment]
I will look at this today or tomorrow.

**Comment by blochealth** [comment]
@travist This WAS gone and came back with 4.5.0 release.

**Comment by travist** [comment]
should be fixed with latest. Sorry.
