### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by fzucaro** [formio/angular-formio#424]
I would know if is possible to have in angular-formio a way to have the breadcrumb bar  clickable in a wizard form. I saw that in js there is the options called "breadcrumbSettings.clickable".
Thanks

**Comment by travist** [comment]
You can pass in the Form.io renderer options (breadcrumbSettings) using the ```[rendererOptions]``` parameter in the renderer... 

```
<formio [rendererOptions]="{breadcrumbSettings:{clickable: true}}" ....></formio>
```

**Comment by fzucaro** [comment]
I use angular-formio 4.2.3 and i'll put the tag as you said:
<formio  [form]='struttura'
         [rendererOptions]="{breadcrumbSettings:{clickable: false}}"
         [submission]='{
      "data": data
        }'
         [options]="options"
         (submit)="onSubmit($event)"
         (change)="onChange($event.data)"
         (nextPage)="onNextPage($event)"
         (prevPage)="onPrevPage($event)"
>
</formio>
but i have the error: Can't bind to 'rendererOptions' since it isn't a known property of 'formio'

**Comment by fzucaro** [comment]
Sorry, i have to include FormManagerModule. It woks fine. Thank you

**Comment by EAGarfield** [comment]
@travist  Hi, I am having the same issue while using rendererOptions

<formio  [options]="options"
 [rendererOptions]="{breadcrumbSettings:{clickable: false}}"
 [form]='formJson'
 (submit)='onFormSubmit($event)'></formio>

 error: Can't bind to 'rendererOptions' since it isn't a known property of 'formio.

 I included the FormioModule and  FormManagerModule and I am still getting the same issue 

Are there any other module solutions?

**Comment by travist** [comment]
It's ```renderOptions``` and not ```rendererOptions```
