### ISSUE TITLE
Create a new Template for Custom component

### ISSUE THREAD

**Issue by Schwofel** [formio/angular-formio#442]
How can i add a new template for my custom component?

**Comment by travist** [comment]
Try these docs. https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements

**Comment by merobal** [comment]
1. Create a new TypeScript file.
Example: `custom-template.ts`

2. Define a single function, with one param called `ctx`. Inside the function define the html. You may reach config via the `ctx` param.
Example:
```
export default function(ctx: any) {
  // console.log(ctx);
  let p = `<div>Lorem Ipsum</div>`;
  return p;
}

```
3. Register the template. Do it "somewhere" in the Angular scope, like in the constructor of an NgModule.
Example:
```
import customTemplate from './custom-template';
import { Templates } from 'angular-formio';

[...]
export class FormDesignerModule {
  constructor() {
    Templates.current.custom = {
      form: fieldTemplate,
    };
  }
}

```
4. You can use this template for your custom formio component. The template will be called "custom" (due to defined as `Templates.current.custom`)
See the "Optional: define a template for the element." part in the docs.

_If you found this useful I can add this to the wiki at some point._

**Comment by hbaldwinRPT** [comment]
Okay but shouldnt it be customTemplate not fieldTemplate? Im doing this and its stating that my template file is not a module. and how do i use this template in my formiocustomcomponent options?

Amazing work on this so far, Cant wait to see how this all works out!
