### ISSUE TITLE
How to add filename and size in FILE component? I have created a custom upload functionality to upload files to server.

### ISSUE THREAD

**Issue by paramjeetnandal** [formio/angular-formio#500]

**Comment by paramjeetnandal** [comment]
ping

**Comment by paramjeetnandal** [comment]
So no answers to this question? I think this is basic functinality of a file uploader. But I found no documentation for this

**Comment by travist** [comment]
For now, this would probably require a custom component that extends the File component. We do not support this currently, and it has not been deemed as high priority for us to fix internally, so we would appreciate the community to jump in here if anyone has done this. The other option is to pay for support or expedite this as a feature in the next release. If you want to go down that road, then please send an email to support at form.io.

**Comment by ullas1989** [comment]
I needed the a file upload component that could post documents to custom API and found that current file upload custom component doesn't have a way to pass JWT token.

I created a custom component by extending ng2-fileupload and then be able to do whatever I need to do inside it.

Negative point is I cannot really share it since code is written as part of angular component. But yes custom component can be used as a work-around.

**Comment by paramjeetnandal** [comment]
Thanks for the response @travist @ullas1989 . Can you please tell me how to extend the file component or any other component in this library. Any working example will be helpful. I am creating a app and may need some other functionalities in future. 
Thanks in advance

**Comment by travist** [comment]
The angular-demo shows how to do it. 

https://github.com/formio/angular-demo/tree/master/src/app/components
